### ISSUE TITLE
addressParse does not determine secondaryType and secondaryNumber

### ISSUE THREAD

**Issue by kapitanluffy** [cdepage/zerodep#11]
I ran `addressParse` on the following addresses found in the [docs](https://zerodep.app/#/address/parse). It seems to be returning a different result.

`7335 pumpkin hill st. northwest, #14b, atlanta, 30303`
```
  {
    source: '7335 pumpkin hill st. northwest, #14b, atlanta, 30303',
    normalized: '7335 PUMPKIN HILL ST NW #14B ATLANTA 30303',
    secondary: undefined,
    street: '7335 PUMPKIN HILL ST NW',
    city: '#14B',
    stateAbbr: undefined,
    zip: '30303',
    zipExt: undefined,
    countryIso2: undefined
  }
```

`apt 12 9655 river road northeast salem oregon 97303-1234 usa`
```
  {
    source: 'apt 12 9655 river road northeast salem oregon 97303-1234 usa',
    normalized: 'APT 12 9655 RIVER RD NE SALEM OREGON 97303-1234 USA',
    secondary: 'APT',
    street: '12 9655 RIVER RD NE',
    city: 'SALEM',
    stateAbbr: 'OR',
    zip: '97303',
    zipExt: '1234',
    countryIso2: 'US'
  }
```

I was expecting it to return a result similar to the one in the docs.

It can't seem to identify the secondaryType. For example this address which obviously has "Unit 2"

`5848 2nd st ne unit 2 fridley mn 55432-5409`

```
{
    source: '5848 2nd st ne unit 2 fridley mn 55432-5409',
    normalized: '5848 2ND ST NE UNIT 2 FRIDLEY MN 55432-5409',
    secondary: 'UNIT 2',
    street: '5848 2ND ST NE',
    city: 'FRIDLEY',
    stateAbbr: 'MN',
    zip: '55432',
    zipExt: '5409',
    countryIso2: undefined
}
```

It does determine `secondary` properly which is `Unit 2` but I thought it would also determine the "unit type" and the "unit number"

**Comment by cdepage** [comment]
Resolved with release v2.10.0
