### ISSUE TITLE
import { isPojo } from '@zerodep/is-pojo' gives error in javascript

### ISSUE THREAD

**Issue by chrisjameslennon** [cdepage/zerodep#5]
Using plain javascript (i.e. not typescript) in NodeJS 20 the line `import { isPojo } from '@zerodep/is-pojo`

gives error:
`import { isPojo } from '@zerodep/is-pojo';
         ^^^^^^
SyntaxError: Named export 'isPojo' not found. The requested module '@zerodep/is-pojo' is a CommonJS module, which may not support all module.exports as named exports.`

Please can you fix or suggest a work-around. thanks

**Comment by cdepage** [comment]
Hi @chrisjameslennon ,

I'm investigating in the next few hours. Please standby....

**Comment by cdepage** [comment]
Hi @chrisjameslennon,

I've published a new patch version. Please let me know if this resolves your issue.

**Comment by cdepage** [comment]
Hi @chrisjameslennon,

Thanks for reporting this issue. Indeed there was a bug with how packages are exported when `"type": "module"` is present the `package.json` file of users of this library and when NOT using typescript.

v2.0.6 of @zerodep/is-pojo resolves this issue.

**Comment by chrisjameslennon** [comment]
this resolves the issue - thank you
