### ISSUE TITLE
ojbect with circular reference causes isPojo to error out with 'maximum call stack exceeded'

### ISSUE THREAD

**Issue by chrisjameslennon** [cdepage/zerodep#7]
```javascript

    var obj = { a: 1, b: 2, c: [3, 4] };
    obj.c.push(obj);

    console.log(isPojo(obj))
```

This code (which has a circular reference at property `c`) errors out with  
`RangeError: Maximum call stack size exceeded
    at isAllowedJSONProperty (file://.../node_modules/@zerodep/is-pojo/esm.mjs:1:546)`

**Comment by cdepage** [comment]
Hi @chrisjameslennon,

I appreciate your time finding and reporting these issues!

v2.0.7 of @zerodep/is-pojo resolves this issue.
